//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekhane_otomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Menü
    {
        public int ID { get; set; }
        public string AnaYemek { get; set; }
        public Nullable<System.DateTime> Tarih { get; set; }
        public Nullable<int> OgunID { get; set; }
        public string YanYemek { get; set; }
        public string AraSıcak { get; set; }
        public string Tatli { get; set; }
        public Nullable<decimal> Maliyet { get; set; }
        public string Salata { get; set; }
        public Nullable<int> Kapasite { get; set; }
        public Nullable<int> YiyenKisiSayisi { get; set; }
    
        public virtual Ogün Ogün { get; set; }
    }
}
