//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekhane_otomasyon.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DBYemekhaneEntities : DbContext
    {
        public DBYemekhaneEntities()
            : base("name=DBYemekhaneEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Admin> Admin { get; set; }
        public virtual DbSet<Departmanlar> Departmanlar { get; set; }
        public virtual DbSet<GorevDetaylar> GorevDetaylar { get; set; }
        public virtual DbSet<Gorevler> Gorevler { get; set; }
        public virtual DbSet<Personel> Personel { get; set; }
        public virtual DbSet<Yemekhaneler> Yemekhaneler { get; set; }
        public virtual DbSet<Menü> Menü { get; set; }
        public virtual DbSet<Ogün> Ogün { get; set; }
        public virtual DbSet<Kullanicilar> Kullanicilar { get; set; }
    }
}
