//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Yemekhane_otomasyon.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ogün
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ogün()
        {
            this.Menü = new HashSet<Menü>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<System.TimeSpan> BaslangicSaati { get; set; }
        public Nullable<System.TimeSpan> BitisSaati { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Menü> Menü { get; set; }
    }
}
